{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2023-26302",
	"modified": "2024-10-15T14:11:24Z",
	"published": "2023-02-22T23:15:00Z",
	"related": [
		"CVE-2023-26302"
	],
	"details": "Denial of service could be caused to the command line interface of markdown-it-py, before v2.2.0, if an attacker was allowed to use invalid UTF-8 characters as input.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:22.04:LTS",
				"name": "markdown-it-py",
				"purl": "pkg:deb/ubuntu/markdown-it-py?arch=src?distro=jammy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"1.1.0-1",
				"1.1.0-2"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2023/UBUNTU-CVE-2023-26302.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2023-26302"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/executablebooks/markdown-it-py/commit/53ca3e9c2b9e9b295f6abf7f4ad2730a9b70f68c"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2023-26302"
		}
	]
}
