{
	"schema_version": "1.6.0",
	"id": "USN-4478-1",
	"modified": "2020-08-31T17:48:35.041087Z",
	"published": "2020-08-31T17:48:35.041087Z",
	"related": [
		"CVE-2020-13757",
		"UBUNTU-CVE-2020-13757"
	],
	"summary": "python-rsa vulnerability",
	"details": "It was discovered that Python-RSA incorrectly handled certain ciphertexts.\nAn attacker could possibly use this issue to obtain sensitive information.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:14.04:LTS",
				"name": "python-rsa",
				"purl": "pkg:deb/ubuntu/python-rsa@3.1.2-1ubuntu0.1+esm1?arch=source&distro=trusty"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.1.2-1ubuntu0.1+esm1"
						}
					]
				}
			],
			"versions": [
				"3.1.2-1",
				"3.1.2-1ubuntu0.1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-rsa",
						"binary_version": "3.1.2-1ubuntu0.1+esm1"
					},
					{
						"binary_name": "python3-rsa",
						"binary_version": "3.1.2-1ubuntu0.1+esm1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-4478-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-4478-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2020-13757"
		}
	]
}
