{
	"schema_version": "1.6.0",
	"id": "USN-4821-1",
	"modified": "2021-03-15T21:58:09.529837Z",
	"published": "2021-03-15T21:58:09.529837Z",
	"related": [
		"CVE-2017-5992",
		"UBUNTU-CVE-2017-5992"
	],
	"summary": "openpyxl vulnerability",
	"details": "It was discovered that openpyxl incorrectly handled certain documents. A\nremote attacker could possibly use this issue to cause a denial of service\nor other unspecified impact.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:16.04:LTS",
				"name": "openpyxl",
				"purl": "pkg:deb/ubuntu/openpyxl@2.3.0-1ubuntu0.1~esm1?arch=source&distro=esm-apps/xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.3.0-1ubuntu0.1~esm1"
						}
					]
				}
			],
			"versions": [
				"2.3.0~b1-1ubuntu1",
				"2.3.0-1"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python-openpyxl",
						"binary_version": "2.3.0-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-openpyxl",
						"binary_version": "2.3.0-1ubuntu0.1~esm1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-4821-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-4821-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2017-5992"
		}
	]
}
