{
	"schema_version": "1.6.0",
	"id": "USN-5138-1",
	"modified": "2021-11-10T22:09:54.489651Z",
	"published": "2021-11-10T22:09:54.489651Z",
	"related": [
		"CVE-2020-29651",
		"UBUNTU-CVE-2020-29651"
	],
	"summary": "python-py vulnerability",
	"details": "\nThe py.path.svnwc component of py (aka python-py) through v1.9.0 contains \na regular expression with an ambiguous subpattern that is susceptible to \ncatastrophic backtracing. This could be used by attackers to cause a compute-time \ndenial of service attack by supplying malicious input to the blame functionality.\n\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:18.04:LTS",
				"name": "python-py",
				"purl": "pkg:deb/ubuntu/python-py?arch=src?distro=bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.5.2-1ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"1.4.34-2ubuntu1",
				"1.4.34-3",
				"1.5.2-1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "pypy-py",
						"binary_version": "1.5.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-py",
						"binary_version": "1.5.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-py",
						"binary_version": "1.5.2-1ubuntu0.1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-5138-1.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "python-py",
				"purl": "pkg:deb/ubuntu/python-py?arch=src?distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.8.1-1ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"1.8.0-1",
				"1.8.0-1build2",
				"1.8.1-1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "pypy-py",
						"binary_version": "1.8.1-1ubuntu0.1"
					},
					{
						"binary_name": "python-py",
						"binary_version": "1.8.1-1ubuntu0.1"
					},
					{
						"binary_name": "python3-py",
						"binary_version": "1.8.1-1ubuntu0.1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-5138-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-5138-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2020-29651"
		}
	]
}
