{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2017-5992",
	"modified": "2017-02-15T19:59:00Z",
	"published": "2017-02-15T19:59:00Z",
	"related": [
		"CVE-2017-5992",
		"USN-4821-1"
	],
	"details": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:16.04:LTS",
				"name": "openpyxl",
				"purl": "pkg:deb/ubuntu/openpyxl?arch=src?distro=esm-apps/xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.3.0-1ubuntu0.1~esm1"
						}
					]
				}
			],
			"versions": [
				"2.3.0~b1-1ubuntu1",
				"2.3.0-1"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python-openpyxl",
						"binary_version": "2.3.0-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-openpyxl",
						"binary_version": "2.3.0-1ubuntu0.1~esm1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2017/UBUNTU-CVE-2017-5992.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:18.04:LTS",
				"name": "openpyxl",
				"purl": "pkg:deb/ubuntu/openpyxl?arch=src?distro=bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.4.9-1"
						}
					]
				}
			],
			"versions": [
				"2.3.0-3"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-openpyxl",
						"binary_version": "2.4.9-1"
					},
					{
						"binary_name": "python3-openpyxl",
						"binary_version": "2.4.9-1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2017/UBUNTU-CVE-2017-5992.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "openpyxl",
				"purl": "pkg:deb/ubuntu/openpyxl?arch=src?distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.4.9-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-openpyxl",
						"binary_version": "2.4.9-1"
					},
					{
						"binary_name": "python3-openpyxl",
						"binary_version": "2.4.9-1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2017/UBUNTU-CVE-2017-5992.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2017-5992"
		},
		{
			"type": "REPORT",
			"url": "http://www.openwall.com/lists/oss-security/2017/02/07/5"
		},
		{
			"type": "REPORT",
			"url": "https://bitbucket.org/openpyxl/openpyxl/issues/749"
		},
		{
			"type": "REPORT",
			"url": "https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2017-5992"
		}
	]
}
