{
	"schema_version": "1.6.0",
	"id": "USN-4204-1",
	"modified": "2019-11-28T12:44:01.148489Z",
	"published": "2019-11-28T12:44:01.148489Z",
	"related": [
		"CVE-2019-18874",
		"UBUNTU-CVE-2019-18874"
	],
	"summary": "python-psutil vulnerability",
	"details": "Riccardo Schirone discovered that psutil incorrectly handled certain\nreference counting operations. An attacker could use this issue to cause\npsutil to crash, resulting in a denial of service, or possibly execute\narbitrary code.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:16.04:LTS",
				"name": "python-psutil",
				"purl": "pkg:deb/ubuntu/python-psutil?arch=src?distro=xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.4.2-1ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"2.2.1-3",
				"3.4.1-1",
				"3.4.2-1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-psutil",
						"binary_version": "3.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-psutil-dbg",
						"binary_version": "3.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-psutil-doc",
						"binary_version": "3.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-psutil",
						"binary_version": "3.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-psutil-dbg",
						"binary_version": "3.4.2-1ubuntu0.1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-4204-1.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:18.04:LTS",
				"name": "python-psutil",
				"purl": "pkg:deb/ubuntu/python-psutil?arch=src?distro=bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.4.2-1ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"5.0.1-1build2",
				"5.4.1-1",
				"5.4.2-1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-psutil",
						"binary_version": "5.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-psutil-dbg",
						"binary_version": "5.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-psutil-doc",
						"binary_version": "5.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-psutil",
						"binary_version": "5.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-psutil-dbg",
						"binary_version": "5.4.2-1ubuntu0.1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-4204-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-4204-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2019-18874"
		}
	]
}
