{
	"schema_version": "1.6.0",
	"id": "USN-6019-1",
	"modified": "2023-04-13T21:17:10.830291Z",
	"published": "2023-04-13T21:17:10.830291Z",
	"related": [
		"CVE-2020-25032",
		"UBUNTU-CVE-2020-25032"
	],
	"summary": "python-flask-cors vulnerability",
	"details": "It was discovered that Flask-CORS did not properly escape paths before\nevaluating resource rules. An attacker could possibly use this to\nexpose sensitive information.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "python-flask-cors",
				"purl": "pkg:deb/ubuntu/python-flask-cors?arch=src?distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.0.8-2ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"3.0.8-2"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python3-flask-cors",
						"binary_version": "3.0.8-2ubuntu0.1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-6019-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-6019-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2020-25032"
		}
	]
}
