{
	"schema_version": "1.6.0",
	"id": "USN-6553-1",
	"modified": "2023-12-12T17:47:24.487103Z",
	"published": "2023-12-12T17:47:24.487103Z",
	"related": [
		"CVE-2021-29510",
		"UBUNTU-CVE-2021-29510"
	],
	"summary": "pydantic vulnerability",
	"details": "Nina Jensen discovered that Pydantic incorrectly handled user input in the\ndate and datetime fields. An attacker could possibly use this issue to\ncause a denial of service via application crash. (CVE-2021-29510)\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:20.04:LTS",
				"name": "pydantic",
				"purl": "pkg:deb/ubuntu/pydantic?arch=src?distro=esm-apps/focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.2-1ubuntu0.1~esm1"
						}
					]
				}
			],
			"versions": [
				"0.30.1-1",
				"1.2-1"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python3-pydantic",
						"binary_version": "1.2-1ubuntu0.1~esm1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-6553-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-6553-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2021-29510"
		}
	]
}
