{
	"schema_version": "1.6.0",
	"id": "USN-3402-1",
	"modified": "2017-08-24T12:02:11.945077Z",
	"published": "2017-08-24T12:02:11.945077Z",
	"related": [
		"CVE-2016-10149",
		"UBUNTU-CVE-2016-10149"
	],
	"summary": "python-pysaml2 vulnerability",
	"details": "It was discovered that PySAML2 incorrectly handled certain\nSAML XML requests and responses. A remote attacker could use\nthis issue to read arbitrary files.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:16.04:LTS",
				"name": "python-pysaml2",
				"purl": "pkg:deb/ubuntu/python-pysaml2@3.0.0-3ubuntu1.16.04.1?arch=source&distro=xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.0.0-3ubuntu1.16.04.1"
						}
					]
				}
			],
			"versions": [
				"2.4.0-0ubuntu2",
				"3.0.0-3ubuntu1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-pysaml2",
						"binary_version": "3.0.0-3ubuntu1.16.04.1"
					},
					{
						"binary_name": "python-pysaml2-doc",
						"binary_version": "3.0.0-3ubuntu1.16.04.1"
					},
					{
						"binary_name": "python3-pysaml2",
						"binary_version": "3.0.0-3ubuntu1.16.04.1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-3402-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-3402-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2016-10149"
		}
	]
}
