{
	"schema_version": "1.6.0",
	"id": "USN-3407-1",
	"modified": "2017-08-30T18:52:29.565935Z",
	"published": "2017-08-30T18:52:29.565935Z",
	"related": [
		"CVE-2017-11424",
		"UBUNTU-CVE-2017-11424"
	],
	"summary": "pyjwt vulnerability",
	"details": "It was discovered that a vulnerability in PyJWT doesn't check\ninvalid_strings properly for some public keys. A remote attacker\ncould take advantage of a key confusion to craft JWTs from scratch.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:16.04:LTS",
				"name": "pyjwt",
				"purl": "pkg:deb/ubuntu/pyjwt?arch=src?distro=xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.3.0-1ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"1.0.0-0ubuntu1",
				"1.3.0-1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-jwt",
						"binary_version": "1.3.0-1ubuntu0.1"
					},
					{
						"binary_name": "python3-jwt",
						"binary_version": "1.3.0-1ubuntu0.1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-3407-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-3407-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2017-11424"
		}
	]
}
