{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2020-11538",
	"modified": "2025-01-13T10:22:11Z",
	"published": "2020-06-25T19:15:00Z",
	"related": [
		"CVE-2020-11538",
		"USN-4430-1",
		"USN-4430-2"
	],
	"details": "In libImaging/SgiRleDecode.c in Pillow through 7.0.0, a number of out-of-bounds reads exist in the parsing of SGI image files, a different issue than CVE-2020-5311.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:18.04:LTS",
				"name": "pillow",
				"purl": "pkg:deb/ubuntu/pillow@5.1.0-1ubuntu0.3?arch=source&distro=bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.1.0-1ubuntu0.3"
						}
					]
				}
			],
			"versions": [
				"4.1.1-3build2",
				"4.3.0-2ubuntu1",
				"5.0.0-1",
				"5.1.0-1",
				"5.1.0-1ubuntu0.2"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-pil",
						"binary_version": "5.1.0-1ubuntu0.3"
					},
					{
						"binary_name": "python-pil-dbg",
						"binary_version": "5.1.0-1ubuntu0.3"
					},
					{
						"binary_name": "python-pil-doc",
						"binary_version": "5.1.0-1ubuntu0.3"
					},
					{
						"binary_name": "python-pil.imagetk",
						"binary_version": "5.1.0-1ubuntu0.3"
					},
					{
						"binary_name": "python-pil.imagetk-dbg",
						"binary_version": "5.1.0-1ubuntu0.3"
					},
					{
						"binary_name": "python3-pil",
						"binary_version": "5.1.0-1ubuntu0.3"
					},
					{
						"binary_name": "python3-pil-dbg",
						"binary_version": "5.1.0-1ubuntu0.3"
					},
					{
						"binary_name": "python3-pil.imagetk",
						"binary_version": "5.1.0-1ubuntu0.3"
					},
					{
						"binary_name": "python3-pil.imagetk-dbg",
						"binary_version": "5.1.0-1ubuntu0.3"
					}
				],
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-11538.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "pillow",
				"purl": "pkg:deb/ubuntu/pillow@7.0.0-4ubuntu0.1?arch=source&distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "7.0.0-4ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"6.1.0-1",
				"6.1.0-1build1",
				"6.2.1-2",
				"7.0.0-4",
				"7.0.0-4build1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-pil-doc",
						"binary_version": "7.0.0-4ubuntu0.1"
					},
					{
						"binary_name": "python3-pil",
						"binary_version": "7.0.0-4ubuntu0.1"
					},
					{
						"binary_name": "python3-pil-dbg",
						"binary_version": "7.0.0-4ubuntu0.1"
					},
					{
						"binary_name": "python3-pil.imagetk",
						"binary_version": "7.0.0-4ubuntu0.1"
					},
					{
						"binary_name": "python3-pil.imagetk-dbg",
						"binary_version": "7.0.0-4ubuntu0.1"
					}
				],
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-11538.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "pillow-python2",
				"purl": "pkg:deb/ubuntu/pillow-python2@6.2.1-3?arch=source&distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"6.2.1-3~build1",
				"6.2.1-3"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-11538.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2020-11538"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/python-pillow/Pillow/pull/4538"
		},
		{
			"type": "REPORT",
			"url": "https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html"
		},
		{
			"type": "REPORT",
			"url": "https://pillow.readthedocs.io/en/stable/releasenotes/index.html"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-4430-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-4430-2"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2020-11538"
		}
	]
}
